version: '3.8'

services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: npm run test
    ports:
      - 9323:9323
    environment:
      - NODE_ENV=production
