version: '3.8'

services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: npm run test
    depends_on:
      - app
    environment:
      - NODE_ENV=production

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: npm run install:all